services:
  - type: web
    name: gmail-clone-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/gmail-clone-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/.jdk
