services:
  - type: web
    name: gmail-clone-backend
    runtime: java
    env: java
    buildCommand: chmod +x mvnw && ./mvnw clean install && mvn package
    startCommand: java -jar target/gmail-clone-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/.jdk
      - key: PORT
        value: 8080
